# Generated by Django 3.0.6 on 2021-05-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='right_answer',
        ),
    ]
