# Generated by Django 2.2.3 on 2020-02-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200222_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='level',
            new_name='level_no',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='questions',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Is this a correct answer?'),
        ),
        migrations.AlterField(
            model_name='level',
            name='mcq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Questions'),
        ),
    ]
