# Generated by Django 2.2.3 on 2020-02-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200222_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='mcq',
        ),
    ]
