# Generated by Django 2.2.3 on 2020-02-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_level_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_flag',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='level',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
