# Generated by Django 2.2.3 on 2020-02-23 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200223_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
