# Generated by Django 2.2.3 on 2020-02-26 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20200225_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='score',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
